# Generated by Django 2.1.3 on 2018-12-07 11:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=254)),
                ('rating', models.FloatField()),
                ('type', models.CharField(max_length=254)),
                ('cuisines', models.CharField(max_length=254)),
                ('cost', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('features', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
