# Generated by Django 2.1.5 on 2019-05-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_short_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='org_logo/')),
                ('address', models.CharField(max_length=260)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('fax', models.CharField(max_length=50)),
                ('p_o_box', models.CharField(max_length=80)),
                ('permit_number', models.CharField(max_length=15)),
                ('permit_date', models.CharField(max_length=10)),
                ('board_members', models.TextField()),
                ('info', models.TextField()),
                ('goals', models.TextField()),
                ('projects', models.TextField()),
                ('permit', models.BooleanField(default=False)),
                ('org_links', models.URLField(blank=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('bank_account_short_info', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='user_photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('bank_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Bank')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City')),
            ],
            options={
                'ordering': ('org_name',),
            },
        ),
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='org_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrgType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.State'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='organization',
            index_together={('id', 'slug')},
        ),
    ]
