# Generated by Django 2.2 on 2019-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('place', models.CharField(db_index=True, max_length=500)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
