# Generated by Django 2.1.3 on 2018-12-06 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='serial',
            field=models.CharField(default=datetime.datetime(2018, 12, 6, 12, 5, 14, 646469, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
