# Generated by Django 2.1.3 on 2018-12-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagla', '0003_remove_restaurant_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(),
        ),
    ]
