# Generated by Django 2.1.3 on 2018-12-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagla', '0005_auto_20181207_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='mpoly',
        ),
    ]
