# Generated by Django 2.1.3 on 2018-12-07 10:53

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pagla', '0006_remove_restaurant_mpoly'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.GeometryField(default=datetime.datetime(2018, 12, 7, 10, 53, 49, 820474, tzinfo=utc), srid=4326),
            preserve_default=False,
        ),
    ]
