# Generated by Django 2.1.3 on 2018-12-07 10:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagla', '0007_restaurant_mpoly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPointField(dim=models.FloatField(), srid=4326, verbose_name=models.FloatField()),
        ),
    ]
