# Generated by Django 2.0.4 on 2019-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_auto_20180304_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.FloatField(null=True),
        ),
    ]
