# Generated by Django 2.1.4 on 2018-12-08 11:39

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartrestaurant',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(23.163401, 89.218163), srid=4326),
        ),
    ]
