# Generated by Django 2.1.4 on 2018-12-08 11:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0002_auto_20181208_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartrestaurant',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
