# Generated by Django 2.1.4 on 2018-12-08 12:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0003_auto_20181208_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('rating', models.FloatField()),
                ('category', models.CharField(max_length=254)),
                ('descriptio', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
