# Generated by Django 2.1.4 on 2018-12-09 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0005_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.utils.timezone.now, srid=4326),
            preserve_default=False,
        ),
    ]
