# Generated by Django 2.1.4 on 2018-12-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0006_hospital_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Hospital1',
        ),
    ]
