# Generated by Django 2.1.4 on 2018-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0007_auto_20181209_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital1',
            name='hospital_n',
            field=models.CharField(max_length=255),
        ),
    ]
