# Generated by Django 2.1.4 on 2018-12-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0008_auto_20181209_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital1',
            new_name='Hospital555',
        ),
    ]
