# Generated by Django 2.1.4 on 2018-12-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city', '0009_auto_20181209_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital555',
            new_name='Hospital55',
        ),
    ]
